variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see https://aka.ms/avm/telemetry.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
}

variable "resource_group_name" {
  type        = string
  description = <<DESCRIPTION
The name of the resource group where the resources will be deployed.
DESCRIPTION
}

variable "name" {
  type        = string
  default     = "acctvnet"
  description = <<DESCRIPTION
The name of the virtual network to create.
DESCRIPTION
}

variable "address_space" {
  type        = string
  default     = "10.0.0.0/16"
  description = <<DESCRIPTION
The address space that is used by the virtual network.
DESCRIPTION
}

variable "address_spaces" {
  type        = list(string)
  default     = []
  description = <<DESCRIPTION
The list of the address spaces that is used by the virtual network.
DESCRIPTION
}

variable "dns_servers" {
  type        = list(string)
  default     = []
  description = <<DESCRIPTION
The DNS servers to be used with vNet.
If no values are specified, this defaults to Azure DNS.
DESCRIPTION
}

variable "vnet_location" {
  type        = string
  default     = null
  description = <<DESCRIPTION
The location/region where the virtual network is created. Changing this forces a new resource to be created.
DESCRIPTION
}
variable "subnets" {
  description = "Configuration for each subnet."
  type = list(object({
    name                                          = string
    address_prefix                              = string
    nsg_id                                        = optional(string,"")
    route_table_id                                = optional(string,"")
    private_endpoint_network_policies_enabled     = optional(bool,"false")
    private_link_service_network_policies_enabled = optional(bool,"false")
    service_endpoints                             = optional(list(string))
    route_table_id      = optional(string)
    delegation = optional(list(object({
      name = string
      service_delegation = object({
        name    = string
        actions = optional(list(string))
      })
    })))
  }))
  default = []
}
variable "ddos_protection_plan" {
  type = object({
    enable = bool
    id     = string
  })
  default     = null
  description = <<DESCRIPTION
The set of DDoS protection plan configuration.
DESCRIPTION
}

variable "tracing_tags_enabled" {
  type        = bool
  default     = false
  description = <<DESCRIPTION
Whether enable tracing tags that generated by BridgeCrew Yor.
DESCRIPTION
  nullable    = false
}

variable "tracing_tags_prefix" {
  type        = string
  default     = "avm_"
  description = <<DESCRIPTION
Default prefix for generated tracing tags.
DESCRIPTION
  nullable    = false

}


variable "tags" {
  type = map(any)
  default = {

  }
  description = <<DESCRIPTION
The tags to associate with your network and subnets.
DESCRIPTION
}

//required AVM interfaces

variable "diagnostic_settings" {
  type = map(object({
    name                                     = optional(string, null)
    log_categories_and_groups                = optional(set(string), ["VMProtectionAlerts"])
    metric_categories                        = optional(set(string), ["AllMetrics"])
    log_analytics_destination_type           = optional(string, "Dedicated")
    workspace_resource_id                    = optional(string, null)
    storage_account_resource_id              = optional(string, null)
    event_hub_authorization_rule_resource_id = optional(string, null)
    event_hub_name                           = optional(string, null)
    marketplace_partner_resource_id          = optional(string, null)
  }))
  default  = {}
  nullable = false

  validation {
    condition     = alltrue([for _, v in var.diagnostic_settings : contains(["Dedicated", "AzureDiagnostics"], v.log_analytics_destination_type)])
    error_message = "Log analytics destination type must be one of: 'Dedicated', 'AzureDiagnostics'."
  }
}


variable "role_assignments" {
  type = map(object({
    role_definition_id_or_name             = string
    principal_id                           = string
    description                            = optional(string, null)
    skip_service_principal_aad_check       = optional(bool, false)
    condition                              = optional(string, null)
    condition_version                      = optional(string, null)
    delegated_managed_identity_resource_id = optional(string, null)
  }))
  default = {}

}

variable "lock" {
  type = object({
    name = optional(string, null)
    kind = optional(string, "None")


  })
  description = "The lock level to apply to the Virtual Network. Default is `None`. Possible values are `None`, `CanNotDelete`, and `ReadOnly`."
  default     = {}
  nullable    = false
  validation {
    condition     = contains(["CanNotDelete", "ReadOnly", "None"], var.lock.kind)
    error_message = "The lock level must be one of: 'None', 'CanNotDelete', or 'ReadOnly'."
  }
}
